[workspace]
name = "nnUNet_contact_seg"
version = "0.1.0"
description = "Automatic contact segmentation BIDS app"
authors = ["Arun Thurairajah <a.thurairajah1@gmail.com>"]
platforms = ["linux-64"]
channels = ["conda-forge"]

[tasks]
nnunet_contact_seg = "python ./nnunet_contact_seg/run.py"

[dependencies]
python = ">=3.10,<4.0"

[pypi-dependencies]
snakebids = "==0.14.0"
nnunetv2 = ">=2.5.1"
scikit-image = ">=0.25.0"
torch = ">=2.5.1"
torchaudio = ">=2.5.1"
torchvision = ">=0.20.1"
antspyx = ">=0.5.4"


