rule reg_qc:
    input: 
        ct_img=bids(
            root=config["output_dir"],
            datatype="registration",
            space="T1w",
            suffix="ct.nii.gz",
            **inputs["post_ct"].wildcards,
        ),
        t1w_img=bids(
            root=config["output_dir"],
            suffix="T1w",
            desc="n4biascorr",
            datatype="n4biascorr",
            extension=".nii.gz",
            **inputs["pre_t1w"].wildcards,
        ),
    output: 
        html=bids(
            root=config["output_dir"],
            datatype="qc",
            desc="reg_qc",
            suffix=".html",
            **inputs["post_ct"].wildcards,
        )
    script: '../scripts/reg_qc.py'

rule contacts_qc:
    input: 
        ct_img=bids(
            root=config["output_dir"],
            datatype="registration",
            space="T1w",
            suffix="ct.nii.gz",
            **inputs["post_ct"].wildcards,
        ),
        t1w_img=bids(
            root=config["output_dir"],
            suffix="T1w",
            desc="n4biascorr",
            datatype="n4biascorr",
            extension=".nii.gz",
            **inputs["pre_t1w"].wildcards,
        ),
        contact_fcsv_labelled=bids(
            root=config["output_dir"],
            suffix="labelled_nnUNet.fcsv",
            **inputs["post_ct"].wildcards,
        ),
        contact_fcsv_planned=config["contacts_fcsv_planned"]
    output: 
        html=bids(
            root=config["output_dir"],
            datatype="qc",
            desc="contacts_qc",
            suffix=".html",
            **inputs["post_ct"].wildcards,
        )
    script: '../scripts/contacts_qc.py'