rule qc:
    input: 
        ct_img=bids(
            root=config["bids_dir"],
            suffix="ct",
            datatype="ct",
            session="post",
            acq="Electrode",
            extension=".nii.gz",
            **inputs["post_ct"].wildcards,
        ),
        t1w_img=bids(
            root=config["bids_dir"],
            suffix="T1w",
            session="pre",
            run="02",
            datatype="anat",
            extension=".nii.gz",
            **inputs["pre_t1w"].wildcards,
        ),
        contact_seg=bids(
            root=config["output_dir"],
            suffix="dseg.nii.gz",
            desc="contacts_nnUNet",
            **inputs["post_ct"].wildcards,
        ),
        contact_fcsv_labelled=bids(
            root=config["output_dir"],
            suffix="labelled_nnUNet.fcsv",
            **inputs["post_ct"].wildcards,
        ),
    output: 
        html=bids(
            root=config["output_dir"],
            datatype="qc",
            desc="qc",
            suffix=".html",
            **inputs["post_ct"].wildcards,
        )
    script: '../scripts/qc.py'